#!/usr/bin/env bash
set -Eeuo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"; cd "${ROOT_DIR}"
REQUIRED_PYTHON="/Users/wwiras/Documents/src/AHBN_GKEProj/venv_ahbn2/bin/python"; PYTHON="${PYTHON:-${REQUIRED_PYTHON}}"; IMAGE="${IMAGE:-}"; MODE="${1:-}"; RESUME=0
EXPECTED_CONTEXT="${EXPECTED_CONTEXT:-gke_stoked-cosine-415611_us-central1-a_bcgossip-cluster}"; NAMESPACE="${NAMESPACE:-ahbn-k7-exp11}"; RELEASE="${RELEASE:-ahbn}"; STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
EXPECTED_IMAGE_DIGEST="${EXPECTED_IMAGE_DIGEST:-sha256:5b7f83e25429abb83925779d65a01f3041dbe2291073a944b61ada706b70fea0}"
CURRENT_STAGE=preflight; CURRENT_SEED=N/A; CURRENT_TREATMENT=N/A
fail(){ echo "ERROR: $*" >&2; exit 1; }; on_error(){ s=$?; echo "FAILED stage=${CURRENT_STAGE} seed=${CURRENT_SEED} treatment=${CURRENT_TREATMENT} command=${BASH_COMMAND} status=${s} output=${RESULT_ROOT:-not-created}" >&2; exit "$s"; }; trap on_error ERR
[ "${MODE}" = smoke ] || [ "${MODE}" = formal ] || fail "Usage: IMAGE=... $0 smoke|formal [--resume RESULT_ROOT]"
if [ "${2:-}" = "--resume" ]; then [ "$#" -eq 3 ] || fail "--resume requires RESULT_ROOT"; RESUME=1; case "$3" in /*) RESUME_ROOT="$3";; *) RESUME_ROOT="${ROOT_DIR}/$3";; esac; elif [ "$#" -ne 1 ]; then fail "Usage: IMAGE=... $0 smoke|formal [--resume RESULT_ROOT]"; fi
[ -x "${PYTHON}" ] && [ "${PYTHON}" = "${REQUIRED_PYTHON}" ] || fail "required Python mismatch: ${PYTHON}"; [ -n "${IMAGE}" ] || fail "IMAGE is mandatory"
for n in kubectl helm shasum; do command -v "$n" >/dev/null || fail "missing command: $n"; done
[ "$(kubectl config current-context)" = "${EXPECTED_CONTEXT}" ] || fail "unexpected kubectl context"; kubectl auth can-i delete pods -n "${NAMESPACE}" | grep -qx yes || fail "pod-delete authorization unavailable"
if [ "${MODE}" = smoke ]; then seeds=(42); DEFAULT_ROOT="${ROOT_DIR}/outputs/k7_exp11_smoke-${STAMP}"; else seeds=(42 43 44 45 46); DEFAULT_ROOT="${ROOT_DIR}/outputs/k7_exp11_formal-${STAMP}"; fi
if [ "$RESUME" -eq 1 ]; then RESULT_ROOT="$RESUME_ROOT"; [ -d "$RESULT_ROOT" ] || fail "resume root does not exist: $RESULT_ROOT"; [ -f "$RESULT_ROOT/image.txt" ] || fail "resume image provenance missing"; [ "$(<"$RESULT_ROOT/image.txt")" = "$IMAGE" ] || fail "resume image differs from original"; GOSSIP_PODS="$RESULT_ROOT/runs/seed42/gossip/pods.json"; [ -f "$GOSSIP_PODS" ] || fail "Gossip pod provenance missing"; "${PYTHON}" -c 'import json,sys; p=json.load(open(sys.argv[1])); image=sys.argv[2]; digest=sys.argv[3]; items=p.get("items",[]); assert len(items)==20, f"expected 20 pods, got {len(items)}"; assert all(x["spec"]["containers"][0]["image"]==image for x in items), "pod image tag mismatch"; ids=[x["status"]["containerStatuses"][0]["imageID"] for x in items]; assert all(digest in value for value in ids), f"pod image digest mismatch: {sorted(set(ids))}"' "$GOSSIP_PODS" "$IMAGE" "$EXPECTED_IMAGE_DIGEST" || fail "existing Gossip image provenance invalid"; else RESULT_ROOT="${RESULT_ROOT:-${DEFAULT_ROOT}}"; fi
mkdir -p "${RESULT_ROOT}"/{configs,generated,runs,results,raw}; exec > >(tee -a "${RESULT_ROOT}/terminal.log") 2>&1
if [ "$RESUME" -eq 1 ]; then date -u +%FT%TZ >"${RESULT_ROOT}/resumed_utc.txt"; echo "RESUME ROOT: ${RESULT_ROOT}"; else printf '%s\n' "${IMAGE}" >"${RESULT_ROOT}/image.txt"; git rev-parse HEAD >"${RESULT_ROOT}/git_commit.txt"; date -u +%FT%TZ >"${RESULT_ROOT}/started_utc.txt"; kubectl -n "${NAMESPACE}" get statefulset peer -o jsonpath='{.spec.template.spec.containers[0].imageID}' >"${RESULT_ROOT}/image_digest.txt" 2>/dev/null || true; fi
HASH_FILES=(app/ahbn_controller.py app/peer.py app/k5_final_actuator_policy.py app/k5_final_actuator_runtime.py app/k6_controller.py app/k6_final_actuator_policy.py app/k6_final_actuator_runtime.py app/k6_exp10_tools.py scripts/run_k6_exp10.sh scripts/k6_exp10_analysis.py experiments/k6_exp10.yaml tests/test_k6_exp10.py app/Dockerfile.k6_exp10 scripts/build_k6_exp10_image.sh)
if [ "$RESUME" -eq 1 ]; then [ -f "${RESULT_ROOT}/immutable_hashes_before.txt" ] || fail "original immutable hash record missing"; shasum -a 256 "${HASH_FILES[@]}" >"${RESULT_ROOT}/immutable_hashes_resume.txt"; cmp "${RESULT_ROOT}/immutable_hashes_before.txt" "${RESULT_ROOT}/immutable_hashes_resume.txt" || fail "K5/K6 immutable hashes differ from original smoke"; else shasum -a 256 "${HASH_FILES[@]}" >"${RESULT_ROOT}/immutable_hashes_before.txt"; fi
"${PYTHON}" -m pytest -q tests/test_k7_exp11.py tests/test_k6_exp10.py tests/test_k5_final_actuator_gke.py
algorithms=(gossip structured dcsoc ahbn)
for seed in "${seeds[@]}"; do generated=(); for algorithm in "${algorithms[@]}"; do cfg="${RESULT_ROOT}/configs/${algorithm}_seed${seed}.yaml"; topo="${RESULT_ROOT}/generated/${algorithm}_seed${seed}.json"; "${PYTHON}" app/k7_exp11_tools.py config --base experiments/k7_exp11.yaml --out "$cfg" --algorithm "$algorithm" --seed "$seed"; "${PYTHON}" app/k7_gen_topology.py --config "$cfg" --out "$topo"; generated+=("$topo"); done; "${PYTHON}" app/k7_exp11_tools.py contract "${generated[@]}"; done
TOPOLOGY_BACKUP="${RESULT_ROOT}/raw/helm_topology_before.json"; cp helm/ahbn/topology.json "$TOPOLOGY_BACKUP"; restore(){ cp "$TOPOLOGY_BACKUP" helm/ahbn/topology.json; }; trap restore EXIT
for seed in "${seeds[@]}"; do for algorithm in "${algorithms[@]}"; do CURRENT_STAGE="GKE run"; CURRENT_SEED="$seed"; CURRENT_TREATMENT="$algorithm"; run="${RESULT_ROOT}/runs/seed${seed}/${algorithm}"; cfg="${RESULT_ROOT}/configs/${algorithm}_seed${seed}.yaml"; rel="${cfg#${ROOT_DIR}/}"; if [ -d "$run" ]; then [ "$RESUME" -eq 1 ] || fail "existing run requires explicit --resume: $run"; cmp "${RESULT_ROOT}/generated/${algorithm}_seed${seed}.json" "$run/topology.json" || fail "existing run topology differs from regenerated frozen contract: $run"; "${PYTHON}" app/k7_exp11_tools.py run --run-dir "$run"; printf 'validated existing run at %s\n' "$(date -u +%FT%TZ)" >"$run/resume_validation.txt"; echo "SKIP VALID COMPLETE RUN seed=${seed} treatment=${algorithm}"; continue; fi; OUTDIR="$run" NAMESPACE="$NAMESPACE" RELEASE="$RELEASE" IMAGE="$IMAGE" PYTHON="$PYTHON" scripts/run_k7_experiment.sh "$rel"; cp "${RESULT_ROOT}/generated/${algorithm}_seed${seed}.json" "$run/topology_role_mapping.json"; "${PYTHON}" app/k7_exp11_tools.py run --run-dir "$run"; grep '"event": "dcsoc_maintenance"' "$run/logs.jsonl" >"$run/dcsoc_maintenance_trace.jsonl" || true; grep -E '"event": "(ahbn_controller_trace|k5_final_actuator_decision|neighbor_unavailable_observed)"' "$run/logs.jsonl" >"$run/ahbn_adaptive_trace.jsonl" || true; done; done
CURRENT_STAGE=analysis; "${PYTHON}" scripts/k7_exp11_analysis.py --root "$RESULT_ROOT" --mode "$MODE"; shasum -a 256 "${HASH_FILES[@]}" >"${RESULT_ROOT}/immutable_hashes_after.txt"; cmp "${RESULT_ROOT}/immutable_hashes_before.txt" "${RESULT_ROOT}/immutable_hashes_after.txt"
trap - EXIT; restore; trap - ERR; echo "K7 Exp11 ${MODE} PASS: ${RESULT_ROOT}"
